### ISSUE TITLE
Trying Out examples.streams.StreamResource

### ISSUE THREAD

**Issue by sshark** [gvolpe/pfps-examples#306]
I am trying to use examples.streams.StreamResource with the following code,

```
object RunMeResource extends IOApp {
  override def run(args: List[String]): IO[ExitCode] =
    StreamResource
      .make[IO]
      .use(bg => bg.schedule(IO(println("happy")), 3.second)) *>
      IO.sleep(5.seconds) *> // (A)
      IO.pure(ExitCode.Success)
}

```
but it waits for 5 seconds before it terminates without printing anything. If I remove the 5 seconds of sleep in (A) the code terminates immediately without printing anything

How do I use StreamResource the right way? Thanks

https://github.com/gvolpe/pfps-examples/blob/e49adf61fe5cdc84b0ca50995f20fb5a79f91cea/src/main/scala/examples/streams/StreamResource.scala

**Comment by gvolpe** [comment]
The `schedule` function is being canceled as part of the resource release. You need to synchronize the termination of your processes, for example:

```scala
object RunMeResource extends IOApp.Simple {

  def run: IO[Unit] =
    IO.deferred[Unit].flatMap { lock =>
      StreamResource
        .make[IO]
        .use {
          _.schedule(
            IO.println("happy") *> lock.complete(()).void,
            3.seconds
          ) *> lock.get
        }
    }

}
```
