### ISSUE TITLE
"Regions of sharing" snippet bug

### ISSUE THREAD

**Issue by einepeople** [gvolpe/pfps-examples#63]
First edition, **ch.2 "Shared state"**, p. 37, "Regions of sharing".
The following code snippet from the book looks incorrect:

```
import cats.effect._
import cats.effect.concurrent.Semaphore
import cats.effect.implicits._
import cats.implicits._
import scala.concurrent.duration._

object SharedState extends IOApp {

  // Not present in the book, added for compilability
  def putStrLn(str: String): IO[Unit] = IO(println(str))

  def someExpensiveTask: IO[Unit] = {
    IO.sleep(1.second) >> putStrLn("expensive task") >> someExpensiveTask
  }

  def p1(s: Semaphore[IO]): IO[Unit] = s.withPermit(someExpensiveTask) >> p1(s)

  def p2(s: Semaphore[IO]): IO[Unit] = s.withPermit(someExpensiveTask) >> p2(s)

  override def run(args: List[String]): IO[ExitCode] =
    Semaphore[IO](1).flatMap { sem =>
      p1(sem).start.void *> p2(sem).start.void
    } *>
      IO.never.as(ExitCode.Success)
}
```

`someExpensiveTask` definition is recurring, whereas the snippet semantics assumes recurrence only at `p1` and `p2` definitions. 
What actually happens is that `p2` locks the semaphore and launches an infinite loop of `someExpensiveTask` executing itself recursively. The very first `withPermit` call is never finished and the semaphore is never unlocked.

What the author probably meant is:

```
def someExpensiveTask: IO[Unit] = {
    IO.sleep(1.second) >> putStrLn("expensive task")
  }
```
For the sake of visualization I have also changed the code a bit to explicitly illustrate, whether `p1` or `p2` called the task:

```
  def someTask(x:Int): IO[Unit] = {
    IO.sleep(1.second) >> putStrLn("SomeTask called by " ++ x.toString)
  }

  def p1(s:Semaphore[IO]):IO[Unit] = s.withPermit(someTask(1)) >> p1(s)

  def p2(s:Semaphore[IO]):IO[Unit] = s.withPermit(someTask(2)) >> p2(s)

  override def run(args: List[String]): IO[ExitCode] =
    Semaphore[IO](1).flatMap{s => p1(s).start *> p2(s).start} *>
      IO.never.as(ExitCode.Success)
```

In this case, output corresponds to what the reader assumes to see - a list of alternating `SomeTask called by 1` and `SomeTask called by 2`, which means the state sharing actually works and semaphore "owner"  alternates.

Also, this code is not present in the current repo, as far as I can see.

**Comment by gvolpe** [comment]
Thanks for the report. If you own a digital copy, make sure you download the latest version since this issue has been fixed. If you are following along the printed copy, there's not much I can do.

As far as the code, we can probably add it in this repo :+1:

**Comment by einepeople** [comment]
Yep, I have the printed one.
Thanks!
